//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spider_Clue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spider_Clue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Recovery.
        /// </summary>
        public static string AccountRecoveryTitle {
            get {
                return ResourceManager.GetString("AccountRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string BtnAddFriend {
            get {
                return ResourceManager.GetString("BtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string BtnChangePassword {
            get {
                return ResourceManager.GetString("BtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Information.
        /// </summary>
        public static string BtnEditInformation {
            get {
                return ResourceManager.GetString("BtnEditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to desktop.
        /// </summary>
        public static string BtnExitToDesktop {
            get {
                return ResourceManager.GetString("BtnExitToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        public static string BtnFriendRequest {
            get {
                return ResourceManager.GetString("BtnFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Player.
        /// </summary>
        public static string BtnGuestPlayer {
            get {
                return ResourceManager.GetString("BtnGuestPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to Party.
        /// </summary>
        public static string BtnJoinToParty {
            get {
                return ResourceManager.GetString("BtnJoinToParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string BtnPlay {
            get {
                return ResourceManager.GetString("BtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Account.
        /// </summary>
        public static string BtnRecover {
            get {
                return ResourceManager.GetString("BtnRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        public static string BtnSendCode {
            get {
                return ResourceManager.GetString("BtnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code.
        /// </summary>
        public static string BtnVerifyCode {
            get {
                return ResourceManager.GetString("BtnVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the information entered and try again..
        /// </summary>
        public static string CheckInformationEntered {
            get {
                return ResourceManager.GetString("CheckInformationEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been banned.
        /// </summary>
        public static string DlgAccountBanned {
            get {
                return ResourceManager.GetString("DlgAccountBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, invalid information.
        /// </summary>
        public static string DlgInvalidData {
            get {
                return ResourceManager.GetString("DlgInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the registration process. Please try again later..
        /// </summary>
        public static string DlgRegisterError {
            get {
                return ResourceManager.GetString("DlgRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new account registration was successful. Welcome!.
        /// </summary>
        public static string DlgRegisterSuccessful {
            get {
                return ResourceManager.GetString("DlgRegisterSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that the email and password are correct. Unable to log in..
        /// </summary>
        public static string DlgWrongDataForLogin {
            get {
                return ResourceManager.GetString("DlgWrongDataForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has ended. Try joining another one..
        /// </summary>
        public static string GameHasEndedMessage {
            get {
                return ResourceManager.GetString("GameHasEndedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The games is full. Please try joining another one.
        /// </summary>
        public static string GameIsFullMessage {
            get {
                return ResourceManager.GetString("GameIsFullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess .
        /// </summary>
        public static string GuessName {
            get {
                return ResourceManager.GetString("GuessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Recovery.
        /// </summary>
        public static string LblAccountRecoveryTitle {
            get {
                return ResourceManager.GetString("LblAccountRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Verification.
        /// </summary>
        public static string LblAccountVerification {
            get {
                return ResourceManager.GetString("LblAccountVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string LblAudio {
            get {
                return ResourceManager.GetString("LblAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        public static string LblAudioSettingsTitle {
            get {
                return ResourceManager.GetString("LblAudioSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string LblChangeAvatar {
            get {
                return ResourceManager.GetString("LblChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address associated with your account..
        /// </summary>
        public static string LblEmailForRecovery {
            get {
                return ResourceManager.GetString("LblEmailForRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string LblForgotPassword {
            get {
                return ResourceManager.GetString("LblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string LblFriends {
            get {
                return ResourceManager.GetString("LblFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends Request.
        /// </summary>
        public static string LblFriendsRequest {
            get {
                return ResourceManager.GetString("LblFriendsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LblGameCode {
            get {
                return ResourceManager.GetString("LblGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username doesn&apos;t exist in our system.
        /// </summary>
        public static string LblGamerTagError {
            get {
                return ResourceManager.GetString("LblGamerTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gamertag is already in use..
        /// </summary>
        public static string LblGamerTagUsed {
            get {
                return ResourceManager.GetString("LblGamerTagUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, introduce your password to continue.
        /// </summary>
        public static string LblIntroducePassword {
            get {
                return ResourceManager.GetString("LblIntroducePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format. (1-50) eg. spiderclue@gmail.com.
        /// </summary>
        public static string LblInvalidEMail {
            get {
                return ResourceManager.GetString("LblInvalidEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamertag only allows letters and numbers (1-15 characters).
        /// </summary>
        public static string LblInvalidGamerTag {
            get {
                return ResourceManager.GetString("LblInvalidGamerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name only allows letters and spaces (1-50 characters).
        /// </summary>
        public static string LblInvalidLastName {
            get {
                return ResourceManager.GetString("LblInvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name only allows letters and spaces (1-50 characters).
        /// </summary>
        public static string LblInvalidName {
            get {
                return ResourceManager.GetString("LblInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have uppercase and lowercase letters, symbols and at least one digit (8-45 characters).
        /// </summary>
        public static string LblInvalidPassword {
            get {
                return ResourceManager.GetString("LblInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English(EUA).
        /// </summary>
        public static string LblLanguageEnglish {
            get {
                return ResourceManager.GetString("LblLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string LblLanguageSettingTitle {
            get {
                return ResourceManager.GetString("LblLanguageSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Mexico).
        /// </summary>
        public static string LblLanguageSpanish {
            get {
                return ResourceManager.GetString("LblLanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LblLastName {
            get {
                return ResourceManager.GetString("LblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LblLevel {
            get {
                return ResourceManager.GetString("LblLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LblLoginTitle {
            get {
                return ResourceManager.GetString("LblLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        public static string LblMusicVolume {
            get {
                return ResourceManager.GetString("LblMusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string LblPasswordRecoveryTitle {
            get {
                return ResourceManager.GetString("LblPasswordRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string LblPasswordsDontMatch {
            get {
                return ResourceManager.GetString("LblPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string LblPasswordWrong {
            get {
                return ResourceManager.GetString("LblPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string LblPersonalInformation {
            get {
                return ResourceManager.GetString("LblPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Edition.
        /// </summary>
        public static string LblProfileEdition {
            get {
                return ResourceManager.GetString("LblProfileEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LblRegister {
            get {
                return ResourceManager.GetString("LblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Icon.
        /// </summary>
        public static string LblSelectIcon {
            get {
                return ResourceManager.GetString("LblSelectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream MainThemeSong {
            get {
                return ResourceManager.GetStream("MainThemeSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream MinecraftButtonSound {
            get {
                return ResourceManager.GetStream("MinecraftButtonSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the game.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results not found.
        /// </summary>
        public static string ResultsNotFoundMessage {
            get {
                return ResourceManager.GetString("ResultsNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
    }
}
